# Generated by Django 4.1.7 on 2023-03-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('manufacture', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('due', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=1000)),
                
            ],
        ),
    ]
