# Generated by Django 4.1.7 on 2023-03-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assist',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assist',
            name='due',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assist',
            name='manufacture',
            field=models.CharField(max_length=100),
        ),
    ]
